### ISSUE TITLE
Running on Windows 10

### ISSUE THREAD

**Issue by ajdevries** [billziss-gh/cgofuse#22]
Nice project, good API and happy that it is also available on Windows.

I'm trying to build a FUSE filesystem for OSX and Windows. Got a part working, but when testing on `Microsoft Windows [Version 10.0.16299.125]` it doesn't work.

Also when testing with memfs.go it doesn't work well on Windows. When running in DEBUG mode I see that all files and directories are uppercase. Some issues that I'm having running memfs:
- can't create a directory and open it in Explorer;
- can't change a file contents;
- see different behaviour when running in CMD and in Explorer.

I'm using the latest WinFSP version.

Can you help me out what is going wrong here?

**Comment by ajdevries** [comment]
After some digging. I found the following user errors ;-)
- I was running the command with a different user is used, and there is some error related to that;
- when using a mountpoint i.e. c:\u there are issues with capitals.

When not using a mountpoint a z: drive is created and that is working okay.

**Comment by billziss-gh** [comment]
File systems on Windows can be mounted as drives or as directories.

Unfortunately file systems mounted as directories must be case-insensitive to function properly. This is because Windows treats file systems mounted as directories as case-insensitive regardless of what the file system reports; it will in many cases lookup files with uppercase names (`FILENAME`) even if the original application did not do so.

This is an unfortunate limitation of the Windows system and it does not happen when the file system is mounted as a drive.

**Comment by ajdevries** [comment]
Thanks for the quick response. Make sense. Will close the issue.
