### ISSUE TITLE
Not able to mount Fuse Drive on a Mapped Network Drive in Windows

### ISSUE THREAD

**Issue by mohankumarv2005** [billziss-gh/cgofuse#33]
I have a mapped network drive (R:) which is pointing one of the folder on the network E.g. "\\server-share\files". When I try to mount FUSE drive to let's say "R:\Fuse" I get below error "Cannot set WinFsp-FUSE file system mount point".

However, I am able to mount Fuse to Local Drive like "C:\Fuse". I have ensured "Fuse" folder is not present.

Any idea on this issue?

**Comment by billziss-gh** [comment]
Can you please post the full FUSE command line that you use to mount the file system (i.e. the arguments to `host.Mount`)?

Keep in mind you cannot mount a "network" file system to a directory. Only "disk" file systems can be mounted on directories.

**Comment by mohankumarv2005** [comment]
Sure, here it is:

options := []string{"-o", "volname=Altair", "-o", "uid=-1", "-o", "gid=-1"}
host.Mount("R:\Fuse", options)

Note: The directory "Fuse" do not exist on R:

**Comment by billziss-gh** [comment]
In order to mount on a directory, WinFsp must be able to set a "reparse point" on the (newly created) directory.

This is done in the WinFsp internal call [`FspFileSystemSetMountPoint_Directory`](https://github.com/billziss-gh/winfsp/blob/v1.5B1/src/dll/fs.c#L289). There are a few reasons why this may fail, but I am suspecting that the problem is that the "reparse point" fails on the network drive.

Is the network drive on a Windows server? For example, I believe there are some issues with reparse points on Samba shares.

**Comment by mohankumarv2005** [comment]
Sorry for delayed response. The Network Server Setup is on Linux (OneFS).
So, it is expected to work?

**Comment by billziss-gh** [comment]
If the server properly supports reparse points (e.g. a Windows server) I believe that it should work.
