### ISSUE TITLE
Not able to mount fuse under a give path multiple times in Linux

### ISSUE THREAD

**Issue by mohankumarv2005** [billziss-gh/cgofuse#34]
I am testing hellofs example in Linux (CentOS 6). For very first time, I mounted successfully under "/root/adrive". When I tried next time to mount under same path, the mount failed without any error. However, it can succesfully mount again with new path E.g. "/root/adrive1".

Can you please help me on this?

**Comment by billziss-gh** [comment]
In Linux FUSE a file system does not get unmounted when the file system process goes away. This is by design in Linux FUSE/libfuse.

Cgofuse uses libfuse underneath and in general works in a similar manner. Cgofuse tries to automatically unmount the file system when it is shutdown in an orderly manner. However when it is forcibly killed it is unable to do so and you must manually use `fusermount` to unmount the file system.
